Use try with resources, keep Gson, updated permission check
playlegend/LegendShowLog pull request #14
Opened 2020-08-10 21:03 UTC by Tobi14601

# Description

Please include a summary of your changes and which issue you fixed. Please also include relevant information and context.
List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] Checkstyle build-step is running without errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

2020-08-10 21:19 UTC, lusu007 commented
Please Adapter the description @tobi14601

2020-08-11 05:23 UTC, ItsKev requested changes

2020-08-11 05:23 UTC, ItsKev commented on bukkit/src/main/java/net/playlegend/legendshowlog/bukkit/ShowLogCommand.java
> +  private static final Gson GSON = new Gson();
only constants should be written in uppercase. https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names
We did this wrong in multiple places. Therefore could you change GSON to gson and EXECUTOR_SERVICE to executorService?

2020-08-11 16:14 UTC, ItsKev approved these changes

2020-08-11 16:14 UTC, merged